apiVersion: v2
name: postiz-app
description: A Social Media Scheduling App 
type: application
version: 1.0.1
appVersion: "1.3.0"
keywords:
  - social media
  - marketing
  - scheduling
  - queue
home: https://postiz.com
sources:
  - https://github.com/gitroomhq/postiz-app
  - https://github.com/gitroomhq/postiz-helmchart
dependencies:
  - name: postgresql
    version: 15.5.28
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
